### ISSUE TITLE
Provide propTypes object

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#232] opened 2019-11-15 12:48 UTC
**Description**

When we are mentioning some arguments passed into a component/function in the documentation, we could also provide the exact propTypes.

For example: https://data-driven-forms.org/renderer/form-controls#formbuttonsrenderprops

We could write there a full propTypes object which an user could just copy, paste and use.

(Or make this object importable from some package - common?)

**Comment by Hyperkid123** [comment] 2020-03-25 08:38
duplicate of #392

**Closed by Hyperkid123** 2020-03-25 08:38 UTC
Labels: P2, common, demo, enhancement
