### ISSUE TITLE
Merging passed initialValues from the schema and from props

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#332] opened 2020-02-27 12:50 UTC
I know that the `initialValues` passed to the `FormRender` component have a higher priority. However, if this attribute is set on the component, it ignores any `initialValue` attributes defined on the field level in the schema, even those which aren't set on the component level.

I discussed this with @rvsia and he said this is a bug, the two levels should be merged with the component level as priority.

**Comment by rvsia** [comment] 2020-02-27 12:52
@Hyperkid123 What do you think?

**Comment by Hyperkid123** [comment] 2020-02-27 13:25
@skateman I was under the impression that initialValue from schema has a higher priority. I will need to think about this for a moment.

**Comment by skateman** [comment] 2020-02-27 13:27
Having the higher priority from the component actually makes more sense, but they should overlap and merge.

**Comment by Hyperkid123** [comment] 2020-02-27 13:30
And how do you think the merge should look like?

**Comment by skateman** [comment] 2020-02-27 15:36
So this setup:
```jsx
const schema = {
  component: 'text-field',
  name: 'name',
},
{
  component: 'text-field',
  name: 'address',
  initialValue: 'Foo street'
},
{
  component: 'text-field',
  name: 'country',
  initialValue: 'Czech Republic'
};

const values = {
  name: 'John Doe',
  address: 'Bar street',
}

<FormRender schema={schema} initialValues={values}>;
```

Should return with the initial values:
```jsx
{
  name: 'John Doe',
  address: 'Bar street',
  country: 'Czech Republic',
}
```

**Comment by Hyperkid123** [comment] 2020-02-27 15:57
@skateman and that is not happening right now? That is how it should work.

**Comment by skateman** [comment] 2020-02-27 15:59
Nope, it doesn't

**Comment by Hyperkid123** [comment] 2020-02-27 16:01
Huh, that is strange. Ok, I will take a look at what is going on there. This is expected behavior and I was under the impression that it is working. Apparently not.

**Comment by Hyperkid123** [comment] 2020-02-28 09:08
@skateman co I just tried the example you posted and I am getting the exact result you wanted.

**Comment by Hyperkid123** [comment] 2020-02-28 09:09
![screenshot-localhost_8080-2020 02 28-10_08_43](https://user-images.githubusercontent.com/22619452/75526601-5d553d80-5a12-11ea-88f1-2686545c21ce.png)

**Comment by skateman** [comment] 2020-02-28 09:27
Maybe the problem is with dotted field names? It's happening on my openstack form in MiQ.

**Comment by Hyperkid123** [comment] 2020-02-28 09:31
Lets try that

**Comment by Hyperkid123** [comment] 2020-02-28 09:33
@skateman 
```JSX
const schema = {fields: [{
    component: 'text-field',
    name: 'name',
  },
  {
    component: 'text-field',
    name: 'bar.address',
    initialValue: 'Foo street'
  },
  {
    component: 'text-field',
    name: 'country',
    initialValue: 'Czech Republic'
  }]};
  
const values = {
name: 'John Doe',
bar: {
    address: 'Bar street',  
    }
}
```

same result as before

**Comment by Hyperkid123** [comment] 2020-02-28 09:34
Maybe try update to latest version? There might have been a bug in previous.

**Comment by skateman** [comment] 2020-02-28 09:52
Still doesn't work with the latest, I have `clearOnUnmount` and `clearedValue={null}`on the form if that helps

**Comment by skateman** [comment] 2020-02-28 09:54
Also it doesn't work for non-dotted fields, it just ignores any `initialValue` coming from the schema if the `initialValues` on the component is set to `{}˙.

**Comment by Hyperkid123** [comment] 2020-02-28 09:56
Hmm. Still can't reproduce. Do you think you could create an example on code sandbox? No need to use any mapper just have some basic inputs.

**Comment by skateman** [comment] 2020-02-28 09:59
I'm afraid it's cause by the fact that the form is being rendered on-demand :confused: so it might be miq-specific...

**Comment by Hyperkid123** [comment] 2020-02-28 10:01
@skateman is it happening in one specific field? Or is there some sort of pattern?

**Comment by skateman** [comment] 2020-02-28 10:06
It's a pattern, every field with an `initialValue` gets ignored in the cloud provider form :confused:

**Comment by Hyperkid123** [comment] 2020-02-28 10:08
Well, that is a big one... Can we check it together on Monday?

**Comment by skateman** [comment] 2020-02-28 10:10
Wednesday the soonest, but sure. It's a tough one ...

**Comment by Hyperkid123** [comment] 2020-03-20 08:11
@skateman closing this seems like the issue was on the MIQ side. Feel free to re-open this issue if you disagree.

**Closed by Hyperkid123** 2020-03-20 08:11 UTC
Labels: P1, bug, renderer
