### ISSUE TITLE
Form validation issue

### ISSUE THREAD

**Issue by regexowl** [data-driven-forms/react-forms#1345] opened 2022-12-07 12:25 UTC
**Scope**: Condition and form validation

**Description**

I've encountered a problem with form validation when using condition `isNotEmpty`.

I've got a form with three radio button options. The first two display a `select list`, the third does not. 

On selection of the first two options the form is only valid when the `select list` is filled in. The third option should be always valid as there is nothing to be filled in.

When the `select list` for the first two options is filled in, I would like to display an additional field.

For that I'm using `isNotEmpty` condition:
```
condition: {

  when: 'field-with-select-list',

  isNotEmpty: true,

},
```

**Problem**
The form isn't valid when the third option is selected, but when I select one of the two with `select list`, fill it in and then select the third option, the form is suddenly valid.

**Expected behavior**
When selecting the third option, the form is valid.

**Screencap**
![ddf-issue](https://user-images.githubusercontent.com/49452678/206178535-a96f5662-e300-407b-8a5e-28dfa84dcd1c.gif)

**Comment by regexowl** [comment] 2022-12-07 14:40
@Hyperkid123 Here it is:

https://github.com/regexowl/image-builder-frontend/blob/bb8b3026d328c4a1aaa23c030c81ad6b5055716e/src/Components/CreateImageWizard/steps/registration.js#L55-L163

I've also tried a bit more complex condition:
```javascript
      condition: {
        and: [
          {
            when: 'subscription-activation-key',
            isNotEmpty: true,
          },
          {
            or: [
              { when: 'register-system', is: 'register-now-insights' },
              { when: 'register-system', is: 'register-now' },
            ],
          },
        ],
      },
```
but the result remained the same.

**Comment by Hyperkid123** [comment] 2022-12-07 17:21
Thank you. I will take a look tomorrow. I have a feeling we might figure this out with some additional configuration.

**Comment by Hyperkid123** [comment] 2022-12-08 10:27
Right I see where the issue is.

The prom is actually this field
```js
  {
    component: componentTypes.PLAIN_TEXT,
    name: 'subscription-activation-key-information',
    label: <Text className="pf-u-danger-color-100 pf-u-font-size-lg">This is the additional information.</Text>,
    condition: {
      when: 'subscription-activation-key',
      isNotEmpty: true,
    },
  },
```

Let me explain why. The validation for the `subscription-activation-key`  field is still present because a reference to the field still exists. In the Form, the `subscription-activation-key` is still registered because the field reference is kept in the condition.

You can check by changing the when the string to something else, the button should now be enabled correctly (`when: 'subscription-activation-key--foobar',`).

How to get around it? Its fairly simple, you wrap the field in a `sub-form` component that has additional conditions.

```js

    {
      component: componentTypes.SUB_FORM,
      name: 'activation-key-info',
      condition: {
        or: [{ when: 'register-system', is: 'register-later' }],
      },
      fields: [
        {
          component: componentTypes.PLAIN_TEXT,
          name: 'subscription-activation-key-information',
          label: <Text className="pf-u-danger-color-100 pf-u-font-size-lg">This is the additional information.</Text>,
          condition: {
            when: 'subscription-activation-key',
            isNotEmpty: true,
          },
        },
      ],
    },
```

This made the validation work for me again.

The fields array now looks like this:
```js
fields: [
    {
      component: componentTypes.RADIO,
      label: 'Register images with Red Hat',
      name: 'register-system',
      // initialValue: 'register-now-insights',
      initialValue: 'register-later',
      options: [
        {
          label: 'Register and connect image instances with Red Hat',
          description: 'Includes Subscriptions and Red Hat Insights',
          value: 'register-now-insights',
          'data-testid': 'radio-register-now-insights',
          autoFocus: true,
        },
        {
          label: 'Register image instances only',
          description: 'Includes Subscriptions only',
          value: 'register-now',
          className: 'pf-u-mt-sm',
          'data-testid': 'radio-register-now',
        },
        {
          label: 'Register later',
          value: 'register-later',
          className: 'pf-u-mt-sm',
          'data-testid': 'radio-register-later',
        },
      ],
    },
    {
      component: 'activation-keys',
      name: 'subscription-activation-key',
      required: true,
      label: (
        <>
          Activation key to use for this image
          <PopoverActivation />
        </>
      ),
      clearOnUnmount: true,
      isRequired: true,
      validateFields: ['register-system'],
      validate: [{ type: validatorTypes.REQUIRED }],
      condition: {
        or: [
          { when: 'register-system', is: 'register-now-insights' },
          { when: 'register-system', is: 'register-now' },
        ],
      },
    },
    {
      component: componentTypes.PLAIN_TEXT,
      name: 'subscription-activation-description',
      label: (
        <>
          Create and manage activation keys in the&nbsp;
          <Button
            component="a"
            target="_blank"
            variant="link"
            icon={<ExternalLinkAltIcon />}
            iconPosition="right"
            isInline
            href="https://access.redhat.com/"
          >
            Customer Portal
          </Button>
        </>
      ),
      condition: {
        or: [
          { when: 'register-system', is: 'register-now-insights' },
          { when: 'register-system', is: 'register-now' },
        ],
      },
    },
    {
      component: componentTypes.PLAIN_TEXT,
      name: 'subscription-register-later',
      label: (
        <TextContent>
          <Text component="h3"> Register Later</Text>
          <Text>On initial boot, systems will need to be registered manually before having access to updates or Red Hat services.</Text>
          <Text>Registering now is recommended.</Text>
        </TextContent>
      ),
      condition: {
        or: [{ when: 'register-system', is: 'register-later' }],
      },
    },
    {
      component: componentTypes.SUB_FORM,
      name: 'activation-key-info',
      condition: {
        or: [{ when: 'register-system', is: 'register-later' }],
      },
      fields: [
        {
          component: componentTypes.PLAIN_TEXT,
          name: 'subscription-activation-key-information',
          label: <Text className="pf-u-danger-color-100 pf-u-font-size-lg">This is the additional information.</Text>,
          condition: {
            when: 'subscription-activation-key',
            isNotEmpty: true,
          },
        },
      ],
    },
  ]
```

**Comment by regexowl** [comment] 2022-12-08 11:02
Hey @Hyperkid123, thanks for looking into this!

Your suggestion fixes the validation issue, but now the first steps don't show the "This is the additional information" anymore after the selection of an activation key.

![Screenshot from 2022-12-08 11-59-21](https://user-images.githubusercontent.com/49452678/206430047-62276e09-e431-4bcf-a362-cf1fb9ceff01.png)

**Comment by Hyperkid123** [comment] 2022-12-08 11:22
Ah, I see. Give me a second, we can fix that :)

**Comment by Hyperkid123** [comment] 2022-12-08 12:12
@regexowl ok based on our little chat and this will be in the future, we will have to use `FormSpy` approach.

I suggest changing the additional information component (the red bit) to use a `FormSpy` and have internal logic for displaying the component without using `useFieldApi` (what Condition internally uses).

The schema and custom component can look something like this:
```jsx
const schemaSnippet =  {
  component: 'additional-information',
  name: 'subscription-activation-key-information',
  label: <Text className="pf-u-danger-color-100 pf-u-font-size-lg">This is the additional information.</Text>,
  valueReference: 'subscription-activation-key',
}
    
const AdditionalInformation = ({ valueReference }) => {
  return (
    <FormSpy>
      {({ values }) =>
        isEmpty(values[valueReference]) ? null : <Text className="pf-u-danger-color-100 pf-u-font-size-lg">This is the additional information.</Text>
      }
    </FormSpy>
  );
};
```

**Comment by regexowl** [comment] 2022-12-08 14:05
@Hyperkid123 thank you! I'll give it a try.

**Closed** 2022-12-12 09:04 UTC
